name: CD

on:
  push:
    tags:
      - 'v*'
    paths:
      - '**.py'
      - '**.cfg'
      - '**.ini'
      - '**.toml'

jobs:
  release-on-push:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Release package
        run: tox -e build,release
        env:
          TWINE_USERNAME: "${{ secrets.TWINE_USERNAME }}"
          TWINE_PASSWORD: "${{ secrets.TWINE_PASSWORD }}"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            dist/*
